### ISSUE TITLE
Add the Composer "replace" configuration

### ISSUE THREAD

**Issue by dankobiaka** [bombayworks/zendframework1#10]
https://getcomposer.org/doc/04-schema.md#replace

Can we get this added so the Bombayworks package can replace the original ZF1 package?

**Comment by glensc** [comment]
you mean https://packagist.org/packages/zendframework/zendframework1 ?

```json
replace: {
   "zendframework/zendframework1": "self.version"
}
```

**Comment by dankobiaka** [comment]
Yes please.

**Comment by deadbeef84** [comment]
Fixed!
