### ISSUE TITLE
PluginLoader

### ISSUE THREAD

**Issue by temp** [bombayworks/zendframework1#3]
We are experiencing problems with the Zend_Form component and the Zend_Loader_PluginLoader.

Since the PluginLoader tries to find the files without autoloading, our own Form Elements are not found.
It would be solved by allowing autoload inside the load() method of the PluginLoader.
We simple changed class_exists($className, false) to class_exists($className, true) and everything worked as expected.

Any chance to get a new version with this improvement?

**Comment by holtkamp** [comment]
no issues with this as well when properly adding the paths in the correct order, think this issue can be closed by now...
