### ISSUE TITLE
Bootstrap loading breaks in 1.12.12

### ISSUE THREAD

**Issue by shaneiseminger** [bombayworks/zendframework1#9]
We get a "Bootstrap class not found" exception after updating to 1.12.12. It seems that there's one require_once() call that should remain active on line 333 of Zend_Application.

```
    if (!class_exists($class, false)) {
        // require_once $path;
        if (!class_exists($class, false)) {
             throw new Zend_Application_Exception(
                'Bootstrap class not found'
             );
        }
    }
```

Disabling this require_once() call makes Zend_Application unable to load the Bootstrap class specified by the bootstrap.class and bootstrap.path config options. To the best of my knowledge the autoloader isn't intended to handle the bootstrap class.

**Comment by shaneiseminger** [comment]
Happy to create a pull request if you prefer.

**Comment by holtkamp** [comment]
:+1:

**Comment by dankobiaka** [comment]
Any update on this? The bombayworks package is completely unusable until this is fixed.

**Comment by mrook** [comment]
+1

**Comment by mrook** [comment]
This can also be fixed by changing one of the class_exists() statements to if (!class_exists($class, true)) {
(to ensure the autoloader is hit)

**Comment by deadbeef84** [comment]
Sorry for the delay, this should now be fixed in 1.12.12 and 1.12.13.

**Comment by glensc** [comment]
@deadbeef84 are you sure the original bug "class not found" error is solved?

**Comment by deadbeef84** [comment]
I'm pretty sure. However, since I updated the existing broken releases, you may need to run `composer clear-cache` to avoid getting old packages.

**Comment by deadbeef84** [comment]
Also, the issues in zf1/zend-application (https://github.com/zf1/zend-application/pull/2) still remains, but it needs a different fix - will try too look into this later this week.
